-- Setup roles for ULEZ project
USE ROLE SECURITYADMIN;

-- Create Roles
CREATE ROLE IF NOT EXISTS ULEZ_ADMIN;
CREATE ROLE IF NOT EXISTS ULEZ_DEVELOPER;

-- Hierarchies (always link to SYSADMIN)
GRANT ROLE ULEZ_ADMIN TO ROLE SYSADMIN;
GRANT ROLE ULEZ_DEVELOPER TO ROLE ULEZ_ADMIN;

-- Database privileges
GRANT USAGE ON DATABASE ULEZ_DB TO ROLE ULEZ_DEVELOPER;
GRANT USAGE ON SCHEMA ULEZ_DB.BRONZE TO ROLE ULEZ_DEVELOPER;
GRANT USAGE ON SCHEMA ULEZ_DB.SILVER TO ROLE ULEZ_DEVELOPER;
GRANT USAGE ON SCHEMA ULEZ_DB.GOLD TO ROLE ULEZ_DEVELOPER;

-- Table privileges
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ULEZ_DB TO ROLE ULEZ_DEVELOPER;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE ULEZ_DB TO ROLE ULEZ_DEVELOPER;

-- Warehouse privileges
GRANT USAGE ON WAREHOUSE ULEZ_WH TO ROLE ULEZ_DEVELOPER;
GRANT OPERATE ON WAREHOUSE ULEZ_WH TO ROLE ULEZ_DEVELOPER;

-- Admin specific privileges
GRANT ALL PRIVILEGES ON DATABASE ULEZ_DB TO ROLE ULEZ_ADMIN;
